services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: form_builder
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    # No need for depends_on in db

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    # Ensure DB is ready before starting (optional improvement later)

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"  # ← Nginx runs on port 80 inside container!
    depends_on:
      - backend
    # No env_file needed unless you have one in frontend

volumes:
  db_data: