name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & Test Backend
        working-directory: ./backend
        run: |
          npm install
          npm test -- --no-coverage

      - name: Install & Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build